const pageTitles: Record<string, string> = {
  "/join": "회원가입",
  "/login": "로그인",
  "/findpw": "비밀번호 재설정",
  "/user/coupon/register": "쿠폰 등록",
  "/user/coupon/published": "쿠폰 발행 목록",
  "/user/coupon/published/deatil": "발행된 쿠폰 통계",
  "/user/main": "사용자 메인화면",
  "/user/notification": "알림함",
  "/user/mypage": "사용자 마이페이지",
  "/mypage/update/phone": "전화번호 변경",
  "/mypage/update/email": "이메일 변경",
  "/general/account": "계정 정보",
  "/user/mypage/usedcoupon": "사용 완료 쿠폰",
  "/user/gift": "선물함",
  "/user/coupon/request": "쿠폰 발행 요청",
  "/user/coupon/request/confirm": "요청서 최종 확인",
  "/user/coupon/request/list": "쿠폰 요청 목록",
  "/user/coupon/request/detail": "쿠폰 발행 요청 상세",
  "/partner/main": "파트너 메인화면",
  "/partner/mypage": "파트너 마이페이지",
  "/partner/statistics": "통계 상세",
  "/partner/orgdetail": "단체별 상세조회",
  "/partner/menudetail": "메뉴별 상세조회",
  "/partner/coupon/scan": "QR 인식",
  "/partner/coupon/status": "쿠폰 상태 관리",
  "/partner/request/auth": "본인 인증",
  "/partner/request/list": "쿠폰 요청 목록",
  "/partner/request/detail": "쿠폰 발행 요청 상세",
  "/partner/request/payment": "결제 정보",
  "/partner/request/approve": "요청 승인 완료",
  "/partner/usedcoupon": "사용 완료 쿠폰",
};

export default pageTitles;
